language: java

dist: trusty

sudo: required

env:
  - JAVAFX_HEADLESS=true

jdk:
  - oraclejdk8

install: true

before_script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

script: mvn clean test

after_success:
  - mvn jacoco:report coveralls:report
